import java.io.* ;
public class CombineStreams {
	public static void main(String args[]) throws IOException
	{
		// declare file streams
		FileInputStream file1 = new FileInputStream( "input.txt");
		FileInputStream file2 = new FileInputStream( "output.txt");
		// declare file3 to store combined streams
		SequenceInputStream file3 = null;
		// concatenate file1 and file2 streams into file3
		file3 = new SequenceInputStream(file1, file2);
		BufferedInputStream inBuffer = new BufferedInputStream(file3);
		BufferedOutputStream outBuffer = new BufferedOutputStream(System.out);
		// read and write combined streams until the end of buffers
		int ch;
		while((ch = inBuffer.read()) != -1)
		outBuffer.write(ch);
		outBuffer.flush(); // check out the output by removing this line
		System.out.println( "\nHello, This output is generated by CombineFiles.java program");
		inBuffer.close();
		outBuffer.close();
		file1.close();
		file2.close();
		file3.close();
	}
}